port: "8080"

db:
  username: "postgres"
  password: "qwerty"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"

rdb:
  addr: "localhost:6379"
  username: ""
  passoword: ""
  db: 0